reportsController:
  rbac:
    clusterRole:
      extraResources:
        - apiGroups:
            - rbac.authorization.k8s.io
          resources:
            - clusterrolebindings
          verbs:
            - get
            - list
            - watch
