apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
  namespace: default
  labels:
    app: vulnerable
    vulnerability: privileged
spec:
  containers:
    - name: privileged-container
      image: nginx:latest
      securityContext:
        privileged: true
      ports:
        - containerPort: 80
